name: check-links
on: [push, pull_request]

jobs:
  build:
    name: Test documentation code examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - run: nix-shell --run "sh bin/test-docs.sh"
        env:
          NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.03.tar.gz
